name: koffer-go
on:
  schedule:
    - cron: '0 23 * * *'
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Login Docker.io
      uses: docker/login-action@v1.14.0
      with:
        logout: true
        registry: docker.io
        username: ${{ secrets.ROBOT_USER_DOCKERHUB }}
        password: ${{ secrets.ROBOT_TOKEN_DOCKERHUB }}

    - name: Login Quay.io
      uses: docker/login-action@v1.14.0
      with:
        logout: true
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Rake Variables
      run: |
        set -x ; \
        echo "varrundate=$(date +%y%m%d%I%M%S)" >> ${GITHUB_ENV};\
        echo;  

    - name: Build Binary
      run: |
        docker run --rm \
            --volume $(pwd):/root/dev:z \
            --volume $(pwd)/bin:/tmp/bin:z \
            --entrypoint /root/dev/build.sh \
          docker.io/${{ secrets.GIT_PROJECT }}/golang

    - name: Build Cradle
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          quay.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}
          quay.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:latest
          quay.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:main-${{ env.varrundate }}-${{ github.sha }}
          docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}
          docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:latest
          docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:main-${{ env.varrundate }}-${{ github.sha }}
        build-args: |
          varRunDate=${{ env.varrundate }}
